# name: readme_app
# description: "A persuasive reading app for kids with personality-based book recommendations"
# publish_to: 'none'

# version: 1.0.0+1

# environment:
#   sdk: '>=3.1.0 <4.0.0'

# dependencies:
#   flutter:
#     sdk: flutter

#   # Firebase Core & Auth (Updated versions)
#   firebase_core: ^2.32.0
#   firebase_auth: ^4.20.0
#   cloud_firestore: ^4.17.5
#   firebase_storage: ^11.7.7

#   # State Management
#   provider: ^6.1.1

#   # Navigation
#   go_router: ^12.1.3

#   # UI & Fonts
#   google_fonts: ^6.1.0
#   cupertino_icons: ^1.0.2

#   # Text-to-Speech
#   flutter_tts: ^3.8.5

#   # Image Loading & Caching
#   cached_network_image: ^3.3.0

#   # Local Storage
#   shared_preferences: ^2.2.2

#   # HTTP Requests
#   http: ^1.1.0

#   # Utilities
#   intl: ^0.18.1

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^3.0.0

# flutter:
#   uses-material-design: true

#   # App Assets - will add these when we have actual assets
#   # assets:
#   #   - assets/images/
#   #   - assets/icons/


name: readme_app
description: "A persuasive reading app for kids with personality-based book recommendations"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core & Auth (Updated to latest versions)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  pdf_text: ^0.5.0
  syncfusion_flutter_pdfviewer: ^30.2.5

  # State Management
  provider: ^6.1.1

  # Navigation
  go_router: ^12.1.3

  # UI & Fonts
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2

  # Text-to-Speech
  flutter_tts: ^3.8.5

  # Image Loading & Caching
  cached_network_image: ^3.3.0

  # Local Storage
  shared_preferences: ^2.2.2

  # HTTP Requests
  http: ^1.1.0

  # Utilities
  intl: ^0.18.1

# Force http version to satisfy all packages
dependency_overrides:
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true