name: readme_app
description: "A persuasive reading app for kids with personality-based book recommendations"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core & Auth (Updated versions)
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2

  # State Management
  provider: ^6.1.5+1

  # Navigation
  go_router: ^16.2.4

  # UI & Fonts
  google_fonts: ^6.3.2
  cupertino_icons: ^1.0.2

  # Text-to-Speech
  flutter_tts: ^4.2.3

  # PDF Viewer
  syncfusion_flutter_pdfviewer: ^31.1.19

  # Alternative PDF Viewer for direct URL support
  pdfx: ^2.4.0

  # Image Loading & Caching
  cached_network_image: ^3.4.1

  # Local Storage
  shared_preferences: ^2.5.3

  # HTTP Requests
  http: ^1.5.0

  # Utilities
  intl: ^0.20.2

# Force compatible versions to prevent conflicts
dependency_overrides:
  http: ^1.5.0
  syncfusion_pdfviewer_platform_interface: ^31.1.19
  syncfusion_pdfviewer_web: ^31.1.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # App Assets - will add these when we have actual assets
  # assets:
  #   - assets/images/
  #   - assets/icons/