// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8krppXLuTXliGvhYMrdnxym9y7Ga-YcA',
    appId: '1:137949170130:web:86abde88af992a8a5e200b',
    messagingSenderId: '137949170130',
    projectId: 'readme-40267',
    authDomain: 'readme-40267.firebaseapp.com',
    storageBucket: 'readme-40267.firebasestorage.app',
    measurementId: 'G-PD8MC3GGMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAASJFLpG1cUxKGSIfZyGozy7qMvP85hKM',
    appId: '1:137949170130:android:d46e3f64b500eb8e5e200b',
    messagingSenderId: '137949170130',
    projectId: 'readme-40267',
    storageBucket: 'readme-40267.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkCIgXsTVSgNqUgkgPnfWXX9QWk1u19OQ',
    appId: '1:137949170130:ios:927889026df4297e5e200b',
    messagingSenderId: '137949170130',
    projectId: 'readme-40267',
    storageBucket: 'readme-40267.firebasestorage.app',
    iosBundleId: 'com.example.readmeTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkCIgXsTVSgNqUgkgPnfWXX9QWk1u19OQ',
    appId: '1:137949170130:ios:927889026df4297e5e200b',
    messagingSenderId: '137949170130',
    projectId: 'readme-40267',
    storageBucket: 'readme-40267.firebasestorage.app',
    iosBundleId: 'com.example.readmeTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8krppXLuTXliGvhYMrdnxym9y7Ga-YcA',
    appId: '1:137949170130:web:2b0f811ab54f792c5e200b',
    messagingSenderId: '137949170130',
    projectId: 'readme-40267',
    authDomain: 'readme-40267.firebaseapp.com',
    storageBucket: 'readme-40267.firebasestorage.app',
    measurementId: 'G-EPDXY8ZX89',
  );

}